blank_issues_enabled: false
contact_links:
  - name: "DM me on Discord"
    url: "https://discord.com/users/828677761303838781"
  - name: "Replit Ask"
    url: "https://ask.replit.com/c/code-help/node-js/25"
