/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**Outputs `message` in red and logs it as an error to ./log, clearing logs older than 24 hours */
export function error(message: string): void;
/**Logs `message` in ./log, clearing logs older than 24 hours */
export function debug(message: string): void;
